# Generated by Django 5.2.3 on 2025-12-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bakong_md5_hash',
            field=models.CharField(blank=True, help_text='MD5 hash for Bakong KHQR payment tracking', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('upload', 'Upload Receipt'), ('bakong_khqr', 'Bakong KHQR'), ('stripe', 'Stripe')], default='upload', max_length=20),
        ),
    ]
