# Generated by Django 5.2.3 on 2026-01-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hidden_by_owner',
            field=models.BooleanField(default=False, help_text='Whether this booking is hidden from property owner view'),
        ),
    ]
