# Generated by Django 5.2.3 on 2026-01-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_hidden_by_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, help_text='When customer actually checked out (different from mark complete)', null=True),
        ),
    ]
