# Generated by Django 5.2.3 on 2026-01-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('still_living', 'Still Living'), ('checked_out', 'Checked Out')], default='pending', max_length=20),
        ),
    ]
