# Generated by Django 5.2.3 on 2025-12-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_qr_code',
            field=models.BooleanField(default=False, help_text='Check if this is a QR code for payment'),
        ),
    ]
