# Generated by Django 5.2.3 on 2025-12-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyimage_is_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='is_qr_code',
        ),
        migrations.AddField(
            model_name='property',
            name='bakong_bank_account',
            field=models.CharField(blank=True, help_text='Bakong bank account in format username@bankcode', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bakong_merchant_name',
            field=models.CharField(blank=True, default='', help_text='Merchant name for KHQR generation', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='bakong_phone_number',
            field=models.CharField(blank=True, default='', help_text='Phone number for KHQR generation', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='use_bakong_payment',
            field=models.BooleanField(default=False, help_text='Enable Bakong KHQR payment for this property'),
        ),
    ]
