# Generated by Django 5.2.3 on 2025-12-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bakong_md5_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('qr_code', 'QR Code'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('bakong_khqr', 'Bakong KHQR')], max_length=20),
        ),
    ]
