# Generated by Django 5.2.3 on 2026-01-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_bakong_md5_hash_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bakong_md5_hash',
            field=models.CharField(blank=True, help_text='MD5 hash for Bakong KHQR payment tracking', max_length=255, null=True),
        ),
    ]
