# Generated by Django 5.2.3 on 2025-12-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ownerevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bakong_account',
            field=models.CharField(blank=True, help_text='Bakong account in format: username@bank', max_length=100),
        ),
    ]
