# Generated by Django 5.2.3 on 2025-12-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bakong_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bakong_account',
        ),
    ]
